name: Publish Extension on VS Marketplace

on:
  push:
    branches:
      - masters
      - "feature/**" #remove this once the testing is done. Need to remove after testing.

    paths-ignore:
      - ".gitignore"
      - ".vscode/**"

jobs:
  cicd:
    name: cicd
    runs-on: ubuntu-18.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: clean install dependencies
        working-directory: pref-monitor-ci
        run: npm ci

      - name: create build && cpy task
        working-directory: pref-monitor-ci
        run: npm run build && npm run copyTask

      - name: pack the task
        working-directory: pref-monitor-ci
        run: npm run pack

      - name: create Extension
        working-directory: pref-monitor-ci
        run: npm run create

      - name: print vsix path
        working-directory: pref-monitor-ci
        run: |
          echo "VISX path:  ${{env.vsix_path}}"

      - name: upload extension to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: vsix-extension
          working-directory: pref-monitor-ci
          path: ${{github.workspace}}/pref-monitor-ci.**.vsix
